name: smart_room_ar
description: Catalogue de mobilier avec visualisation AR, connecte au backend Spring Boot.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  model_viewer_plus: ^1.7.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.2
  share_plus: ^10.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
